### ISSUE TITLE
Skill tree

### ISSUE THREAD

**Issue by mklabs** [mklabs/taurox-beastmen-mod#23]
_From @mklabs on April 18, 2018 19:22_

- [x] Work out the few unique remaining skills
- [x] Remove Ghorros one, rename skill, add correct loc
- [x] Duplicate Kholek skill, rework loc.
- [x] work on loc.
- [x] brass armour anciliary char skill (#15)

_Copied from original issue: mklabs/twmods#16_
